services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6319:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami
  webapp:
    build: webapp/
    ports:
      - 8000:5000
    